cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  file: target/debian/bintray.json
  key: $BINTRAY_KEY
  provider: bintray
  skip_cleanup: true
  user: pauldraper
  on:
    branch: publish
git:
  depth: 1
jdk:
  - oraclejdk8
language: scala
script:
  - sbt 'all debian:bintrayDescriptor admin/debian:packageBin'
